/* SCRIPT PARA LA CREACIÓN DE PROCEDIMIENTOS PARA TYPE CLIENT */

USE SISTEMA_CONTROL_INGRESOS;

/* PROCEDIMIENTO PARA LISTAR TODOS LOS TIPOS DE CLIENTES */
DELIMITER //

CREATE PROCEDURE SelectAllType()
BEGIN
    SELECT ID_TYPE, NAME, STATUS FROM TYPE;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA LISTAR TIPO DE CLIENTE POR ID */
DELIMITER //

CREATE PROCEDURE SelectByIdType(IN Id INT)
BEGIN
    SELECT ID_TYPE, NAME, STATUS 
    FROM TYPE
    WHERE ID_TYPE = Id;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA INSERTAR TIPO DE CLIENTE */
DELIMITER //

CREATE PROCEDURE InsertType(IN Name VARCHAR(255), IN Status VARCHAR(50))
BEGIN
        INSERT INTO TYPE (NAME, STATUS)
        VALUES (Name, 'Active');
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA ACTUALIZAR TIPO DE CLIENTE */
DELIMITER //

CREATE PROCEDURE UpdateType(IN Id INT, IN Name VARCHAR(255), IN Status VARCHAR(50))
BEGIN
    UPDATE TYPE
    SET NAME = Name, STATUS = Status
    WHERE ID_TYPE = Id;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA CAMBIAR EL STATUS DE TIPO DE CLIENTE */
DELIMITER //

CREATE PROCEDURE ToggleTypeStatus(IN Id INT)
BEGIN
    DECLARE CurrentStatus VARCHAR(50);

    -- Obtener el estado actual
    SELECT STATUS INTO CurrentStatus
    FROM TYPE
    WHERE ID_TYPE = Id;

    -- Cambiar el estado a 'Desactivado' si es 'Activado', y viceversa
    IF CurrentStatus = 'Active' THEN
        UPDATE TYPE
        SET STATUS = 'Disabled'
        WHERE ID_TYPE = Id;
    ELSEIF CurrentStatus = 'Disabled' THEN
        UPDATE TYPE
        SET STATUS = 'Active'
        WHERE ID_TYPE = Id;
    END IF;
END;
//

DELIMITER ;
