/* SCRIPT PARA LA CREACIÓN DE PROCEDIMIENTOS PARA CLIENTS */

USE SISTEMA_CONTROL_INGRESOS;

/* PROCEDIMIENTO PARA LISTAR TODOS LOS CLIENTES */
DELIMITER //

CREATE PROCEDURE SelectAllClients()
BEGIN
    SELECT CLIENTS.ID_CLIENT, CLIENTS.NAME, CLIENTS.SECTOR, CLIENTS.LEGAL_ID, CLIENTS.ID_TYPE, TYPE.NAME AS NAME_TYPE, CLIENTS.STATUS
	FROM CLIENTS
	JOIN TYPE ON CLIENTS.ID_TYPE = TYPE.ID_TYPE;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA LISTAR CLIENTE POR ID */
DELIMITER //

CREATE PROCEDURE SelectByIdClient(IN Id INT)
BEGIN
    SELECT CLIENTS.ID_CLIENT, CLIENTS.NAME, CLIENTS.SECTOR, CLIENTS.LEGAL_ID, CLIENTS.ID_TYPE, TYPE.NAME AS NAME_TYPE, CLIENTS.STATUS
	FROM CLIENTS
	JOIN TYPE ON CLIENTS.ID_TYPE = TYPE.ID_TYPE
	WHERE CLIENTS.ID_CLIENT = Id;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA INSERTAR CLIENTE */
DELIMITER //

CREATE PROCEDURE InsertClient(IN Name VARCHAR(255), IN Sector VARCHAR(255), IN Legal_Id VARCHAR(50), IN Id_Type INT)
BEGIN
	INSERT INTO CLIENTS (NAME, SECTOR, LEGAL_ID, ID_TYPE, STATUS)
	VALUES (Name, Sector, Legal_Id, Id_Type, 'Active');
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA ACTUALIZAR CLIENTE */
DELIMITER //

CREATE PROCEDURE UpdateClient(IN Id INT, IN Name VARCHAR(255), IN Sector VARCHAR(255), IN Legal_Id VARCHAR(50), IN Id_Type INT, IN Status VARCHAR(50))
BEGIN
    UPDATE CLIENTS
    SET NAME = Name, SECTOR = Sector, LEGAL_ID = Legal_Id, ID_TYPE = Id_Type, STATUS = Status
    WHERE ID_CLIENT = Id;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA CAMBIAR EL STATUS DE CLIENTE */
DELIMITER //

CREATE PROCEDURE ToggleClientStatus(IN Id INT)
BEGIN
    DECLARE CurrentStatus VARCHAR(50);

    -- Obtener el estado actual
    SELECT STATUS INTO CurrentStatus
    FROM CLIENTS
    WHERE ID_CLIENT = Id;

    -- Cambiar el estado a 'Desactivado' si es 'Activado', y viceversa
    IF CurrentStatus = 'Active' THEN
        UPDATE CLIENTS
        SET STATUS = 'Disabled'
        WHERE ID_CLIENT = Id;
    ELSEIF CurrentStatus = 'Disabled' THEN
        UPDATE CLIENTS
        SET STATUS = 'Active'
        WHERE ID_CLIENT = Id;
    END IF;
END;
//

DELIMITER ;
