/* SCRIPT PARA LA CREACIÓN DE PROCEDIMIENTOS PARA LOGS */

USE SISTEMA_CONTROL_INGRESOS;

/* PROCEDIMIENTO PARA LISTAR TODOS LOS LOGS */
DELIMITER //

CREATE PROCEDURE SelectAllLogs()
BEGIN
    SELECT ID_LOGS, DESCRIPTION, USER, DATE  FROM logs;
END;
//

DELIMITER ;

/* PROCEDIMIENTO PARA INSERTAR LOGS */
DELIMITER //

CREATE PROCEDURE InsertLog(IN Description VARCHAR(255), IN User VARCHAR(50), IN Date VARCHAR(50))
BEGIN
    INSERT INTO logs (DESCRIPTION, USER, DATE)
        VALUES (Description, User, Date);
END;
//

DELIMITER ;

